#include "board.h"
#include "calib.h"
#include "cli.h"
#include "comm.h"
#include "flow.h"
#include "help.h"
#include "misc.h"
#include "od.h"
#include "relay.h"
#include "rtd.h"
#include "valve.h"
#include "wdt.h"

const CliCmdType *gCmdArray[] = {
	&CMD_HELP,
	&CMD_VERSION,
	&CMD_BOARD,
	&CMD_CAL_STATUS,
	&CMD_RTD_TEMP_READ,
	&CMD_RTD_RES_READ,
	&CMD_RTD_RES_CALIB,
	&CMD_WDT_RELOAD,
	&CMD_WDT_GET_PERIOD,
	&CMD_WDT_SET_PERIOD,
	&CMD_WDT_GET_INIT_PERIOD,
	&CMD_WDT_SET_INIT_PERIOD,
	&CMD_WDT_GET_OFF_PERIOD,
	&CMD_WDT_SET_OFF_PERIOD,
	&CMD_WDT_GET_RESET_COUNT,
	&CMD_WDT_CLR_RESET_COUNT,
	&CMD_WATER_READ,
	&CMD_FISH_I_READ,
	&CMD_OD_FISH_READ,
	&CMD_OD_PERI_READ,
	&CMD_OD_FISH_WRITE,
	&CMD_OD_PERI_WRITE,
	&CMD_RELAY_FAN_READ,
	&CMD_RELAY_FAN_WRITE,
	&CMD_RELAY_LIGHT_WRITE,
	&CMD_RELAY_LIGHT_READ,
	&CMD_RELAY_PUMP_WRITE,
	&CMD_RELAY_PUMP_READ,
	&CMD_RELAY_SPARE_WRITE,
	&CMD_RELAY_SPARE_READ,
	&CMD_RELAY_WRITE,
	&CMD_RELAY_READ,
	&CMD_VALVE_STATE_READ,
	&CMD_VALVE_CLOSING_READ,
	&CMD_VALVE_OPENING_READ,
	&CMD_VALVE_OPEN_WRITE,
	&CMD_VALVE_CLOSE_WRITE,
	&CMD_FLOW_CNT_READ,
	&CMD_FLOW_CNT_RESET,
	&CMD_FLOW_FREQ_READ,
	&CMD_COOL_WRITE,
	0
};
